name: add
description: Adds a new version for a specified pre-existing package

inputs:
  package-name:
    description: Package name
    required: true
  version:
    description: Version of the *python* package, NOT necessarily the git tag
    required: true
  link:
    description: Link used for `pip`. For example, hyalus==0.1.0 could be git+https://github.com/genapsysinc/hyalus@0.1.0-1
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        requirements-txt: requirements.txt
    - name: Add New Package Version
      env:
        PKG_ACTION: ADD
        PKG_NAME: ${{ inputs.package-name }}
        PKG_VERSION: ${{ inputs.version }}
        PKG_LINK: ${{ inputs.link }}
      run: python .github/actions.py
      shell: bash
    - name: Create Pull Request
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: peter-evans/create-pull-request@v5
      with:
        branch: add-pkg-version
        commit-message: '📦 [🤖] Add new package version in PyPI index'
        title: '[🤖] Add `${{ inputs.package-name }}==${{ inputs.version }}` to PyPI index'
        body: Automatically generated PR, adding `${{ inputs.package-name }}` version
          ${{ inputs.version }} in PyPI index.
        branch-suffix: random
        delete-branch: true
    - name: Push Commit
      if: ${{ github.event_name == 'workflow_call' }}
      uses: EndBug/add-and-commit@v9
      with:
        add: .
        default_author: github_actions
        message: GitHub Actions - Add ${{ inputs.package-name }} version ${{ inputs.version }}
        push: true
