# Adds a new version for a specified pre-existing package
name: add

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: Package name
        required: true
        type: string
      version:
        description: Version of the *python* package, NOT necessarily the git tag
        required: true
        type: string
      link:
        description: Link used for `pip`. For example, hyalus==0.1.0 could be git+https://github.com/genapsysinc/hyalus@0.1.0-1
        required: true
        type: string

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: GenapsysInc/internal-pypi/actions/add@main
        with:
          package-name: ${{ inputs.package-name }}
          version: ${{ inputs.version }}
          link: ${{ inputs.link }}
          token: ${{ github.token }}
