name: register

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: Package name
        required: true
        type: string
      version:
        description: Version of the *python* package, NOT necessarily the git tag
        required: true
        type: string
      short-desc:
        description: A short description of the package
        required: true
        type: string
      long-desc:
        description: A longer description of the package (HTML)
        required: true
        type: string
      homepage:
        description: Homepage of the package (link to the github repository)
        required: true
        type: string
      link:
        description: Link used for `pip`. For example, hyalus==0.1.0 could be git+https://github.com/genapsysinc/hyalus@0.1.0-1
        required: true
        type: string

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        requirements-txt: requirements.txt
    - name: Register Package
      env:
        PKG_ACTION: REGISTER
        PKG_NAME: ${{ inputs.package-name }}
        PKG_VERSION: ${{ inputs.version }}
        PKG_SHORT_DESC: ${{ inputs.short-desc }}
        PKG_LONG_DESC: ${{ inputs.long-desc }}
        PKG_HOMEPAGE: ${{ inputs.homepage }}
        PKG_LINK: ${{ inputs.link }}
      run: python .github/actions.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: '📦 [🤖] Register ${{ inputs.package-name }} in PyPI index'
        title: '[🤖] Register `${{ inputs.package-name }}` in PyPI index, with version ${{ inputs.version }}'
        body: Automatically generated PR, registering `${{ inputs.package-name }}` in PyPI
          index with version ${{ inputs.version }}.
        branch-suffix: random
        delete-branch: true
